name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main # Trigger workflow on pull requests to main branch

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests (if applicable)
        run: |
          cd backend
          npm test  # Adjust as per your backend testing command

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t backend-image .

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t frontend-image .

  deploy:
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]

    steps:
      - name: Deploy to production
        run: |
          docker run -d -p 3000:3000 backend-image
          docker run -d -p 80:80 frontend-image
